### ISSUE TITLE
Dynamic linking

### ISSUE THREAD

**Issue by arjunguha** [plasma-umass/ElementaryJS#118]
At the moment, ElementaryJS (and Ocelot) has two built-in libraries: (1) the image processing library and (2) the "sane" JavaScript runtime library. We are planning a third for robot control. Every time we make a change to these libraries, we have to rebuild and redeploy Ocelot. This is stupid. I talked to Joydeep about this and came up with the following plan:

- Each library should be available on the web
- There should be a JSON file on the web that maps library names to URLs. E.g.,  at `https//paws.googlecloudstorage.com/libs.json`, we should have the file:

```
{ Math : "https://...",
  lib220: "https://..."
 ...
}
```
- ElementaryJS should export a `require` function that allows the user to `require('lib220')`. Builtins, such as `Math` should be automatically required. The JSON file above thus serves as a whitelist and resolution mechanism for libraries.

The obvious way to implement this is to have ElementaryJS's `require` function dynamically fetch each library. But, this is not going to work well when we have crappy Internet. **A better approach is to have ElementaryJS fetch all libraries when the page is loaded.**

- [ ] Write a separate function that takes a dictionary of URLs / file paths and turns it into a dictionary with code.

We have to also think about how this will work in Gradescope. The obvious approach is to download libraries from the web, even in Gradescope. But, I am concerned that we will suffer spurious network errors. I think a better approach is to modify the compile function in ElementaryJS to take the path to the JSON mapping (edit CompilerOpts):

https://github.com/plasma-umass/ElementaryJS/blob/master/ts/types.ts#L33

If the path is an HTTPS path, it should load it from the web. However, if the path is a file, it should load it from the file. This would allow us to have the libraries available locally in Gradescope. We would even be able to use different versions of a library in a grading environment.

*Note:*: The EJS compile function will have to become asynchron

Comments welcome.

@sp1tz @lchsam @joydeep-b

**Comment by joydeep-b** [comment]
A feature that we will need is to be able to test and hack on the libraries without deploying them. This sounds like we'll need to provide a local mapping JSON somehow. Thoughts? Add a hack that if serving locally use a custom mapping?

**Comment by arjunguha** [comment]
Agreed. As I suggested above, the EJS compile function will take as an argument the path to the JSON mapping. Instead of hard coding that path in Ocelot, we can make it depend on the hostname of the website. So, when the hostname is localhost, we can have it read from somewhere else. Does that sound reasonable?

**Comment by arjunguha** [comment]
The require function goes here:

https://github.com/plasma-umass/ElementaryJS/blob/925dcae6b71830e10abd4677efc0b769cd212b03/ts/index.ts#L45

**Comment by sp1tz** [comment]
I pushed an outline of the implementation based on our discussion today @arjunguha. There still are some things I am unclear on. If others could look and provide comments/suggestions, it would be appreciated.
https://github.com/plasma-umass/ElementaryJS/tree/require

**Comment by sp1tz** [comment]
@arjunguha: @lchsam & I pushed an implementation of require in the case of strictly EJS (_e.g._ Gradescope). The other cases will follow, but we would like some feedback before continuing.

The most significant changes are in the main compile function where we take in a JSON file that contains a map of module names to code paths. It then reads each file in as a string (this is synchronous since we didn't want to deal with making the compile function async for now), creating a new map of module names to code. This is then passed to ElementaryRunner,  where a private member variable stores the contents of the "evaled" code. Our custom require method is made available at runtime; one can use it as traditional require.

We update `compiler.ts` with a basic manual test case. So one could create a JS file that uses the module whitelisted and compile the code to EJS. Note that as the file is now, the mapping is already from module name to code, though it can be edited to an absolute file path to be used as described above. We expect there to be two additional modes; running with Ocelot online & offline, wherein the online case EJS would simply receive the map of module names to code directly from Ocelot.

**Comment by arjunguha** [comment]
The main missing feature at that libraries need to get references to a variety of EJS/Ocelot internals to do any useful work. @sp1tz is on it I believe. A good case study would be if we could write `require("lib220")`. To get that to work, we need libraries to be a function that receive these as inputs:

https://github.com/plasma-umass/ElementaryJS/blob/master/ts/lib220.ts#L1

**Comment by sp1tz** [comment]
https://github.com/umass-compsci220/ocelot-settings/pull/2
What, if anything, will be left for this issue after the PR is merged? IK we'll have to update the prod Ocelot site, but I think feature development will be complete.

**Comment by arjunguha** [comment]
I think we'll be ready to close this issue!
